name: Test Dataset.toml tests
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Test Dataset.toml
        run: |
          pytest tests/test_datasets_toml.py
